version: '3.8'

services:

  dbminiblog:
    image: postgres
    restart: always
    container_name: db_miniblog
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    env_file:
      - .env


  miniblog:
    container_name: api_miniblog
    restart: always
    build: .
    ports:
      - 8000:8000
    links:
      - dbminiblog
    command: uvicorn "app.main:app" --host 0.0.0.0 --reload
    env_file:
      - .env

volumes:
    dbdata:
